.travis.yml
this avoid duplicate builds for push+PR
=> build(travis): only build for commits/pr targeted to master branch

ff4j-spring-boot-web-api/src/main/kotlin/org/ff4j/spring/boot/web/api/resources/FF4jResource.kt
It is a draft PR, comment are welcomed.
=> Add Rest API to check multiple toggles

ff4j-spring-boot-web-api/src/main/kotlin/org/ff4j/spring/boot/web/api/resources/FF4jResource.kt, ff4j-spring-boot-web-api/src/test/java/org/ff4j/spring/boot/web/api/resources/ff4j/FF4JStepDef.java, ff4j-spring-boot-web-api/src/test/resources/features/FF4JResource.feature, ff4j-spring-services/src/main/kotlin/org/ff4j/services/FF4jServices.kt, ff4j-spring-services/src/test/java/org/ff4j/services/ff4j/FF4JServicesStepDef.java
Fix for https://github.com/ff4j/ff4j/issues/449#issuecomment-703093099
FYI: @clun
=> Fix check multi

ff4j-spring-boot-web-api/src/test/resources/features/FF4JResource.feature
Continuation to add test for https://github.com/ff4j/ff4j-spring-boot-starter-parent/pull/150
=> test(web-api): update scenario of multi check feature with execution context

ff4j-spring-boot-web-api/src/main/kotlin/org/ff4j/spring/boot/web/api/resources/FeatureResource.kt, ff4j-spring-boot-web-api/src/main/kotlin/org/ff4j/spring/boot/web/api/resources/PropertyResource.kt, ff4j-spring-boot-web-api/src/main/kotlin/org/ff4j/spring/boot/web/api/utils/FeatureWebUtils.kt, ff4j-spring-boot-web-api/src/test/java/org/ff4j/spring/boot/web/api/resources/feature/FeatureStepDef.java, ff4j-spring-boot-web-api/src/test/java/org/ff4j/spring/boot/web/api/utils/FeatureWebUtilsTest.java, ff4j-spring-boot-web-api/src/test/resources/features/FF4JResource.feature, ff4j-spring-boot-web-api/src/test/resources/features/FeatureResource.feature, ff4j-spring-boot-web-api/src/test/resources/features/PropertyResource.feature
Fix: https://github.com/ff4j/ff4j-spring-boot-starter-parent/issues/184
=> fix(web-api): http status 204 for update operation

ff4j-spring-boot-web-api/src/main/kotlin/org/ff4j/spring/boot/web/api/resources/FeatureResource.kt
Fix https://github.com/ff4j/ff4j-spring-boot-starter-parent/issues/238
=> fix(ff4j-spring-boot-web-api): remove consumes

ff4j-spring-boot-sample/pom.xml, pom.xml
=> build: update assertj-code scope to test and add version to maven-javadoc-plugin

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md, README.md
=> ci: add codeowners, pr template

README.md
=> docs: update title with work-in-progress

ff4j-spring-boot-autoconfigure-webflux/src/main/kotlin/org/ff4j/spring/boot/autoconfigure/webflux/FF4JWebConsoleConfiguration.kt, ff4j-spring-boot-autoconfigure-webmvc/src/main/kotlin/org/ff4j/spring/boot/autoconfigure/webmvc/FF4JWebConsoleConfiguration.kt, ff4j-spring-boot-sample/pom.xml
=> build: bump versions

ff4j-spring-boot-autoconfigure-webflux/src/main/kotlin/org/ff4j/spring/boot/autoconfigure/webflux/FF4JWebConsoleConfiguration.kt, ff4j-spring-rest-api/src/main/kotlin/org/ff4j/spring/rest/api/resources/PropertyResource.kt, ff4j-spring-rest-api/src/main/kotlin/org/ff4j/spring/rest/api/utils/FeatureWebUtils.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/FF4JTestHelperUtils.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/representation/TestAuthorizationsManager.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/resources/feature/FeatureResourceStepDef.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/resources/feature/RunCucumberFeatureResourceTest.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/resources/featurestore/FeatureStoreResourceStepDef.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/resources/featurestore/RunCucumberFeatureStoreResourceTest.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/resources/ff4j/FF4JResourceStepDef.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/resources/group/GroupResourceStepDef.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/resources/monitoring/MonitoringResourceStepDef.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/resources/property/PropertyResourceStepDef.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/resources/propertystore/PropertyStoreResourceStepDef.kt, ff4j-spring-rest-api/src/test/resources/features/FeatureResource.feature, ff4j-spring-services/src/main/kotlin/org/ff4j/services/domain/FF4jStatusApiBean.kt, ff4j-spring-services/src/main/kotlin/org/ff4j/services/domain/FeatureApiBean.kt, ff4j-spring-services/src/main/kotlin/org/ff4j/services/domain/PropertyApiBean.kt, ff4j-spring-services/src/main/kotlin/org/ff4j/services/exceptions/FlippingStrategyBadRequestException.kt, ff4j-spring-services/src/main/kotlin/org/ff4j/services/exceptions/GroupExistsException.kt, ff4j-spring-services/src/test/kotlin/org/ff4j/services/FF4JTestHelperUtils.kt, ff4j-spring-services/src/test/kotlin/org/ff4j/services/domain/DomainTest.kt, ff4j-spring-services/src/test/kotlin/org/ff4j/services/feature/FeatureServicesStepDef.kt, ff4j-spring-services/src/test/kotlin/org/ff4j/services/monitoring/MonitoringServicesStepDef.kt, ff4j-spring-services/src/test/kotlin/org/ff4j/services/representation/TestAuthorizationsManager.kt, ff4j-spring-services/src/test/resources/features/FeatureServices.feature, pom.xml
=> bump versions, fix warnings and fix deprecated code

ff4j-spring-rest-api/src/main/kotlin/org/ff4j/spring/rest/api/resources/FF4jResource.kt, ff4j-spring-rest-api/src/main/kotlin/org/ff4j/spring/rest/api/resources/FeatureResource.kt, ff4j-spring-rest-api/src/main/kotlin/org/ff4j/spring/rest/api/resources/FeatureStoreResource.kt, ff4j-spring-rest-api/src/main/kotlin/org/ff4j/spring/rest/api/resources/GroupResource.kt, ff4j-spring-rest-api/src/main/kotlin/org/ff4j/spring/rest/api/resources/MonitoringResource.kt, ff4j-spring-rest-api/src/main/kotlin/org/ff4j/spring/rest/api/resources/PropertyResource.kt, ff4j-spring-rest-api/src/main/kotlin/org/ff4j/spring/rest/api/resources/PropertyStoreResource.kt, ff4j-spring-rest-api/src/main/kotlin/org/ff4j/spring/rest/api/utils/FeatureWebUtils.kt, ff4j-spring-services/pom.xml, ff4j-spring-services/src/main/kotlin/org/ff4j/services/FF4jServices.kt, ff4j-spring-services/src/main/kotlin/org/ff4j/services/FeatureServices.kt, ff4j-spring-services/src/main/kotlin/org/ff4j/services/FeatureStoreServices.kt, ff4j-spring-services/src/main/kotlin/org/ff4j/services/GroupServices.kt, ff4j-spring-services/src/main/kotlin/org/ff4j/services/MonitoringServices.kt, ff4j-spring-services/src/main/kotlin/org/ff4j/services/PropertyServices.kt, ff4j-spring-services/src/main/kotlin/org/ff4j/services/PropertyStoreServices.kt, ff4j-spring-services/src/test/kotlin/org/ff4j/services/feature/FeatureServicesStepDef.kt, ff4j-spring-services/src/test/kotlin/org/ff4j/services/featurestore/FeatureStoreServicesStepDef.kt, ff4j-spring-services/src/test/kotlin/org/ff4j/services/ff4j/FF4JServicesStepDef.kt, ff4j-spring-services/src/test/kotlin/org/ff4j/services/group/GroupServicesStepDef.kt, ff4j-spring-services/src/test/kotlin/org/ff4j/services/monitoring/MonitoringServicesStepDef.kt, ff4j-spring-services/src/test/kotlin/org/ff4j/services/property/PropertyServicesStepDef.kt, ff4j-spring-services/src/test/kotlin/org/ff4j/services/propertystore/PropertyStoreServicesStepDef.kt, ff4j-spring-services/src/test/resources/features/GroupServices.feature, ff4j-spring-services/src/test/resources/features/PropertyStoreServices.feature
=> feat(service): add non-blocking response from service

README.md
=> docs: update readme with v2 instructions

ff4j-spring-rest-api/src/main/kotlin/org/ff4j/spring/rest/api/exceptions/FF4jExceptionHandler.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/resources/feature/FeatureResourceStepDef.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/resources/featurestore/FeatureStoreResourceStepDef.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/resources/ff4j/FF4JResourceStepDef.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/resources/group/GroupResourceStepDef.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/resources/property/PropertyResourceStepDef.kt, ff4j-spring-rest-api/src/test/kotlin/org/ff4j/spring/rest/api/resources/propertystore/PropertyStoreResourceStepDef.kt, ff4j-spring-rest-api/src/test/resources/features/FF4JResource.feature, ff4j-spring-rest-api/src/test/resources/features/FeatureResource.feature, ff4j-spring-rest-api/src/test/resources/features/FeatureStoreResource.feature, ff4j-spring-rest-api/src/test/resources/features/GroupResource.feature, ff4j-spring-rest-api/src/test/resources/features/PropertyResource.feature, ff4j-spring-rest-api/src/test/resources/features/PropertyStoreResource.feature
Using ProblemDetails for error handling as per RFC 7807
Closes :
=> feat(exception): use ProblemDetails for exceptions handling

ff4j-spring-boot-autoconfigure-webflux/pom.xml, ff4j-spring-boot-autoconfigure-webflux/src/main/kotlin/org/ff4j/spring/boot/autoconfigure/webflux/FF4JWebFluxSecurityConfiguration.kt, ff4j-spring-boot-autoconfigure-webflux/src/main/resources/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, ff4j-spring-boot-autoconfigure-webflux/src/test/kotlin/org/ff4j/spring/boot/autoconfigure/webflux/Application.kt, ff4j-spring-boot-autoconfigure-webflux/src/test/kotlin/org/ff4j/spring/boot/autoconfigure/webflux/FF4JSecurityDisableConfigurationTest.kt, ff4j-spring-boot-autoconfigure-webflux/src/test/kotlin/org/ff4j/spring/boot/autoconfigure/webflux/FF4JSecurityEnableConfigurationTest.kt, ff4j-spring-boot-autoconfigure-webmvc/src/main/kotlin/org/ff4j/spring/boot/autoconfigure/webmvc/FF4JWebMvcSecurityConfiguration.kt, ff4j-spring-boot-autoconfigure-webmvc/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
=> add security configuration for webflux

README.md
=> docs(starter-webflux): update feature spring security

ff4j-spring-services/src/test/kotlin/org/ff4j/services/propertystore/PropertyStoreServicesStepDef.kt, ff4j-spring-services/src/test/resources/features/PropertyStoreServices.feature, pom.xml
=> build: bump version

.github/workflows/build_workflow.yml
=> ci: update version and adapt

pom.xml
=> build: bump version spring 3.4.4 and openapi 2.8.5

.github/workflows/build_workflow.yml
=> ci: update code coverage action to v5

pom.xml
=> build(deps): update cucumber to 7.28.2 and add junit-jupiter dependency
